kind: pipeline
name: default

steps:
- name: Download dart sass and hugo
  image: debian:stable-slim
  commands:
  - '/drone/src/download.sh'
- name: build and publish docker image
  image: plugins/docker
  pull: always
  settings:
    repo: askiiart/hugo
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password