kind: pipeline
name: default

steps:
- name: Download dart sass and hugo
  image: alpine
  commands:
  - curl $(curl -s https://api.github.com/repos/sass/dart-sass/releases/latest | grep "browser_download_url.*dart-sass-.*-linux-x64.tar.gz" | cut -d : -f 2,3 | tr -d \") -LO
  - curl $(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*hugo_.*_linux-amd64.tar.gz" | head --lines 1 | cut -d : -f 2,3 | tr -d \") -LO
  - tar -xf dart-sass-*.tar.gz
  - tar -xf hugo_*_linux-amd64.tar.gz --one-top-level
- name: build and publish docker image
  image: plugins/docker
  pull: always
  settings:
    repo: askiiart/hugo
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password